version: '2'
services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        image: exam-service:latest
        container_name: exam-service-web
        environment:
            DB_CONNECTION: mysql
            DB_PORT: 3306
            DB_HOST: 172.23.0.1
            DB_DATABASE: exam
            DB_USERNAME: root
            DB_PASSWORD: water123
            SERVICE_NAME: exam-service
            SERVICE_KEY: b8vsS5zccSl0weNmaNDrXbKecgyhDR
            SERVICE_SECRET: XKqOdYXspn4xWkEwptY7pg7mXV60icazZIY6iSprqJVI8AOckH
            APP_ENV: development
            APP_KEY: base64:qS1JoSLAELbJS+jrobkLSufg1eIyLZmozWnif07QpzY=
            APP_DEBUG: 1
            APP_TIMEZONE: Asia/Manila
            CACHE_DRIVER: file
            QUEUE_DRIVER: sync
            S3_KEY:
            S3_SECRET:
            S3_REGION:
            S3_BUCKET:
            MAIL_MAILER: smtp
            MAIL_HOST: smtp.googlemail.com
            MAIL_PORT: 465
            MAIL_USERNAME: donotreplyresa@gmail.com
            MAIL_PASSWORD: water123!
            MAIL_ENCRYPTION: ssl
            MAIL_FROM_ADDRESS: donotreplyresa@gmail.com
        ports:
        - 8194:80
        volumes:
        - .:/var/www/html
networks:
    web:
        external: true
